apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: ir-01-quickstart
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProductionFREE
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 300m
              memory: 368Mi
          name: runtime
  logFormat: basic
  defaultNetworkPolicy:
    enabled: true
  replicas: 1
  version: '12.0'
  barURL:
    - >-
      https://db-01-quickstart-dash.cp4i:3443/v1/directories/ExampleValidateJSONproject.generated?2611af70-25c3-4daa-94ce-8f9c809af19d
  configurations: []
  forceFlowsHTTPS:
    enabled: true